import Head from "next/head";
import Banner from "../components/Banner";
import Countdown from "../components/Countdown";
import InfoSection from "../components/InfoSection";
import Regalos from "../components/Regalos";
import Footer from "../components/Farewell";
import styled from "styled-components";
import { useState } from "react";

const HomeContainer = styled.div``;

export default function Home() {
  const [mesaDeRegalosUrl, setMesaDeRegalos] = useState(
    "https://mesaderegalos.liverpool.com.mx/milistaderegalos/50957253"
  );

  return (
    <HomeContainer>
      <Head>
        <title>Nuestra Boda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ring.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Beau+Rivage&family=Birthstone&family=Birthstone+Bounce&family=Corinthia&family=Mea+Culpa&family=Poppins:wght@200;400&display=swap"
          rel="stylesheet"
        />
        <meta name="theme-color" content="#A78556" />
      </Head>
      <Banner title={"Verónica y Guillermo"} subtitle="Nuestra Boda" />
      <Countdown />
      <InfoSection />
      <Regalos
        title="Regalos"
        phrase="Tu presencia es nuestro mayor regalo, pero si quieres tener un detalle con nosotros, puedes visitar nuestra mesa de regalos."
        url={mesaDeRegalosUrl}
      />
      <Footer />
    </HomeContainer>
  );
}
